#pragma once
// We dont need all these this is just a generic HDK include
#include <GA/GA_Attribute.h>
#include <GA/GA_AttributeFilter.h>
#include <GA/GA_ElementWrangler.h>
#include <GA/GA_Handle.h>
#include <GEO/GEO_PrimPoly.h>
#include <GU/GU_Detail.h>
#include <GU/GU_Surfacer.h>
#include <OP/OP_AutoLockInputs.h>
#include <OP/OP_Operator.h>
#include <OP/OP_OperatorTable.h>
#include <OP/OP_Utils.h>
#include <PRM/PRM_TemplateBuilder.h>
#include <SOP/SOP_GraphProxy.h>
#include <SOP/SOP_Node.h>
#include <SOP/SOP_NodeVerb.h>
#include <SYS/SYS_Math.h>
#include <SYS/SYS_Types.h>
#include <UT/UT_DSOVersion.h>
#include <UT/UT_Interrupt.h>
#include <UT/UT_NTStreamUtil.h>
#include <UT/UT_Ramp.h>
#include <UT/UT_SharedPtr.h>
#include <UT/UT_String.h>
#include <UT/UT_StringHolder.h>
#include <UT/UT_StringStream.h>
#include <UT/UT_VectorTypes.h>
#include <UT/UT_VoxelArray.h>
#include <SOP/SOP_Node.h>
#include <PRM/PRM_Include.h>
#include <UT/UT_StringHolder.h>
#include <GU/GU_Detail.h>
#include <GU/GU_PrimPoly.h>
#include <UT/UT_Vector2.h>
#include <UT/UT_Vector3.h>